spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:file:${user.home}/IdeaProjects/spring-kotlin-demo/db
    username: wadek
    password: admin
  jpa:
    hibernate:
      ddl-auto: 'create-drop'

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8090